GET http://localhost:3000/

###
GET http://localhost:3000/sample/

###
GET http://localhost:3000/sample/41

###
POST http://localhost:3000/sample
Content-Type: application/json

{
"name": "Name",
"description": "Description"
}

### UPDATE
PATCH http://localhost:3000/sample/16
Content-Type: application/json

{
"name": "new name",
"description": "new description"
}

###
DELETE http://localhost:3000/sample/16