GET http://localhost:3000/

###
GET http://localhost:3000/sample/

### bad ID for custom exception message testing
GET http://localhost:3000/sample/22

###
POST http://localhost:3000/sample
Content-Type: application/json

{
"description": "new sample POST"
}

### UPDATE
PATCH http://localhost:3000/sample/1
Content-Type: application/json

{
"description": "updated sample"
}

###
DELETE http://localhost:3000/sample/2